# Generated by Django 5.1.4 on 2025-01-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=255)),
                ('description', models.TextField(default=0)),
                ('destination', models.CharField(default=0, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.CharField(default=0, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallary')),
                ('approved', models.BooleanField(default=False, null=True)),
                ('is_top_package', models.BooleanField(default=False)),
                ('is_budget_friendly', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, default=0, help_text='Last date This package is available', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(default=0, max_length=100)),
                ('company_name', models.CharField(default=0, max_length=100)),
                ('email', models.EmailField(default=0, max_length=100)),
                ('contact_info', models.TextField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('number_of_people', models.PositiveBigIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], default='success', max_length=50)),
                ('Booking', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.booking')),
            ],
        ),
    ]
