# Generated by Django 5.1.4 on 2025-01-07 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_tourpackage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.tourpackage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
