# Generated by Django 5.1.4 on 2025-01-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, help_text='Last date This package is available', null=True),
        ),
    ]
