# Generated by Django 5.1.4 on 2025-01-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_booking_number_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tourpackage'),
        ),
    ]
